require('dotenv').config();
const bcrypt=require('bcryptjs');const connectDB=require('../config/database');const User=require('../models/User');const Category=require('../models/Category');const Product=require('../models/Product');const Variant=require('../models/Variant');const SKU=require('../models/SKU');
async function seed(){await connectDB();await Promise.all([User.deleteMany({}),Category.deleteMany({}),Product.deleteMany({}),Variant.deleteMany({}),SKU.deleteMany({})]);
const admin=await User.create({full_name:'Catalog Admin',email:process.env.ADMIN_EMAIL||'admin@example.com',password_hash:await bcrypt.hash(process.env.ADMIN_PASSWORD||'Admin@12345',12),role:'admin'});
const fiction=await Category.create({name:'Fiction',slug:'fiction'});const classics=await Category.create({name:'Classics',slug:'classics',parent_id:fiction._id});const self=await Category.create({name:'Self Help',slug:'self-help'});
const p1=await Product.create({category_id:fiction._id,name:'The Alchemist',slug:'the-alchemist',description:'A philosophical novel.',status:'draft'});const p2=await Product.create({category_id:classics._id,name:'Pride and Prejudice',slug:'pride-and-prejudice',description:'A classic novel.',status:'draft'});const p3=await Product.create({category_id:self._id,name:'Atomic Habits',slug:'atomic-habits',description:'A practical book about habits.',status:'draft'});
const v1=await Variant.create({product_id:p1._id,option_name:'Format',option_value:'Paperback'});const v2=await Variant.create({product_id:p1._id,option_name:'Format',option_value:'Hardcover'});const v3=await Variant.create({product_id:p2._id,option_name:'Format',option_value:'Paperback'});const v4=await Variant.create({product_id:p3._id,option_name:'Format',option_value:'Paperback'});
await SKU.create([{variant_id:v1._id,sku_code:'ALCHEMIST-PB-001',price:'1499.00',stock_quantity:25,is_active:true},{variant_id:v2._id,sku_code:'ALCHEMIST-HC-001',price:'2299.00',stock_quantity:8,is_active:true},{variant_id:v3._id,sku_code:'PAP-PRIDE-001',price:'1299.00',stock_quantity:14,is_active:true},{variant_id:v4._id,sku_code:'ATOMIC-PB-001',price:'1999.00',stock_quantity:0,is_active:false}]);
console.log({admin:admin.email,categories:3,products:3,skus:4});await require('mongoose').connection.close();}
seed().catch(e=>{console.error(e);process.exit(1)});
